#!/bin/sh

ID=$(id -u)

if [ $ID -ne 0]
then 
  echo "ERROR:: this is not the root user. Please run with root access"
  exit 1
else
   echo "you are root user"
fi

yum install mysql -y

if [ $? is -ne 0]
then 
    echo "ERROR:: Installation of MYDQL is failed"
    exit 1
else
    echo "Installation of MYSQK is success"
fi

yum install git -y

if [ $? is -ne 0]
then 
    echo "ERROR:: Installation of GIT is failed"
    exit 1
else
    echo "Installation of GIT is success"
fi